[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "gettext-translator-marianmt"
version = "0.0.1"
description = "MarianMT implementation for translator-service"
authors = [{ name="Rodolfo González González", email="github@rodolfo.gg" }]
readme = "README.md"
license = { text = "Apache 2.0" }
dependencies = [
    "gettext-translator-service>=0.0.1"
]

[project.entry-points."gettext_translator_service.plugins"]
marianmt = "gettext_translator_marianmt:TranslatorMarianMT"
